export const actionConsts = {
    ADD_TO_DO: 'ADD_TO_DO',
    REMOVE_TO_DO: 'REMOVE_TO_DO',
    SELECT_TO_DO: 'SELECT_TO_DO',
    SET_VISIBLE: 'SET_VISIBLE',
    SHOW_ALL: 'SHOW_ALL',
    SHOW_COMPLETED: 'SHOW_COMPLETED',
    SHOW_UNCOMPLETED: 'SHOW_UNCOMPLETED'
}